# ticker
ticker:
      AAPL: 
          RSI: 
            - 14
            - 80
            - 30
          BOLL:
            - 25
            - 2
      GOOGL:
          RSI: 
            - 14
            - 70
            - 30
          BOLL:
            - 25
            - 2
      4661:
          RSI: 
            - 14
            - 70
            - 30
          BOLL:
            - 25
            - 2
      AMD:
          RSI:
            - 14
            - 70
            - 30
          BOLL:
            - 25
            - 2
      KO: 
          RSI: 
            - 14
            - 80
            - 20
          BOLL:
            - 25
            - 2
      TSLA: 
          RSI: 
            - 14
            - 70
            - 20
          BOLL:
            - 25
            - 2
